name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - Makefile
      - .github/workflows/deploy-api.yml

concurrency: deploy-api

jobs:
  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore Yarn cache
        uses: actions/cache@v2
        with:
          path: ./api/node_modules
          key: api-yarn-${{ hashFiles('./api/yarn.lock') }}
          restore-keys: api-yarn-
      - name: Retrieve AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: make api/deploy STAGE=prod
